Add all project files
musangamfure/react-capstone-project pull request #1
Opened 2023-06-30 19:06 UTC by musangamfure

Hello, 

In this PR, I have worked on all features and functionalities of the react-capstone project which in my case the Movie app. 

## Here are what I have done:

**Home page**

    - When the page loads, the webapp shows the list of categories that could be filtered out by some parameter, for example by the category name.
    - Along with the category name, you will display some numeric values per category that come from the API.
    - When the user clicks (or taps) on a category item, the application navigates to the details page.

**Details page**

    - In the details page, the webapp retrieves data from the API to show detailed data in the category.
    - When the user clicks on the "Back" button (<), the user navigates to the home page.

 **Testing requirements**

    - Create unit tests for pure functions in your Redux code.
    - Create integration tests for your application using the React Testing Library.

**Technical requirements**

    - The project is a single-page application (SPA) built with React and Redux.
    - The data retrieved from the API should be stored in the Redux store.
    -  Filter shows from the API using a Filter stateless component by categories.
    - Every page (the main page and the pages for each item) have a unique route within the SPA.
    - The project is deployed and accessible online using [Render](https://render.com/).
    - Link to the online version of the app is in the README file.

Kindly check the project and let me know what you think.

Happy Coding 🎉🎉

2023-06-30 21:04 UTC, vickymarz requested changes
Hi @musangamfure, 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the Git Flow ✅ 
- Good redux setup✅ 
- The PR title and description are professional and descriptive ✅ 
- Tests well written ✅ 
- Good component structure ✅ 
- Linters are working properly ✅ 


## Required Changes ♻️

- [ ] I have gone through your code and its commendable. One major thing you need to take note is that your design doesn't match the design guideline given to you. It is very important to always stick to any design given to you and replicate it as expected. In this regard, I will like you to look critically at the design guideline and make sure to modify your design to match it for both the homepage and the details page 👎🏽 

Design guideline 👇🏽 
![image](https://github.com/musangamfure/react-capstone-project/assets/63473584/623ab629-e614-4b4c-8ff0-f5c265a37661)


_Check the comments under the review._
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-30 21:04 UTC, victorokoroji commented on README.md
> +## 🙏 Acknowledgments <a name="acknowledgements"></a>
- [ ] Kindly ensure that your README contains an "Acknowledgements" section or similar that gives appropriate credit to [Nelson Sakwa](https://www.behance.net/sakwadesignstudio) the [author of the original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), as required by the [Creative Commons License](https://creativecommons.org/licenses/).

2023-07-01 03:32 UTC, codepantha requested changes
# STATUS: CHANGES REQUIRED ♻️

## Hi @musangamfure 👋, 

Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media0.giphy.com/media/rZ10JtoPRv1Ly/giphy.gif"/>

## Highlights 🎯 
✔️ Descriptive PR
✔️ Wrote unit tests 📌 
✔️ Linters are passing 📌 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-01 03:32 UTC, codepantha commented on src/components/Show.js
> +    </div>
- [ ] Please style the item cards to look exactly like the design guideline. Please follow these action steps to get a more similar design: 
1. Please use 2 background colors (a lighter and a darker variant) for the item cards and ensure that they are alternating. This will give it the look of a chequered board (like a chess board) just like in the design
2. Style the arrow icon at the top-right of each card to look just like the one in the design
3. Reduce the height of each card and its image so that it mirrors the cards in the design accurately.
4. Increase the font-size of the text at the bottom of each card in order to get a more accurate design

### Design Guideline
![image](https://github.com/musangamfure/react-capstone-project/assets/46839548/4f9ccd0c-f603-4459-a0bb-050e572c50c6)

### Your Implementation
![image](https://github.com/musangamfure/react-capstone-project/assets/46839548/20f3dbe5-b7d8-4e66-ad67-e097397d8d5e)

2023-07-01 06:01 UTC, tufoinnkuo10 requested changes
## Hi @musangamfure 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Gitflow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Test added
✅ well deployed

Required Changes ♻️
Check the comments under the review

![ttt](https://media.giphy.com/media/QW9DYS2fsdORhO9Phu/giphy.gif)

Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2023-07-01 06:01 UTC, tufoinnkuo10 commented on src/components/ShowDetails.js
> +  const shows = useSelector((state) => state.shows.Shows);
- [ ] Wonderful job so far. Please like the previous reviewer specifically noted and as you can see from the original design, the thick and light color is in a check board form. I.e. a zigzag manner, not one side being thick color and one being lighter like in your case. Kindly use this small change as a way to advance your design skill 😄 💯 
yours
 
![Screenshot (1183)_LI](https://github.com/musangamfure/react-capstone-project/assets/65298048/67b943d8-796c-47e6-8965-58e7fbeeed73)
original design
![Screenshot (1092)_LI](https://github.com/musangamfure/react-capstone-project/assets/65298048/93d4e0bb-c28c-4708-b8d8-b41448c48e6e)

2023-07-01 11:18 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @musangamfure  

Your project is complete! Great job for making the changes🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- Great design
- No linter errors

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

![tufoin](https://media.giphy.com/media/d0NnEG1WnnXqg/giphy.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-01 12:10 UTC, merged